name: 時々変わるデータの差分検出

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の午前0時（UTC）= 日本時間月曜日午前9時
    # - cron: '0 22 * * *'
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Setup repo
        uses: actions/checkout@v5

      - name: キャッシュのリストア
        uses: actions/cache@v4
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      # 中身見たいときだけ使ったほうがいい
      # - run: echo '${{ toJSON(steps) }}'

      - name: クリーンインストール
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: docker compose -f docker-compose.yml run --rm app npm ci

      - name: 差分チェック
        id: diff_check
        continue-on-error: true
        run: docker compose -f docker-compose.yml run --rm app npm run test
      
      - name: 郵便番号ファイルダウンロード
        if: ${{ steps.diff_check.outcome == 'failure' }}
        run:  docker compose run --rm app wget -O ./tmp/current.zip https://www.post.japanpost.jp/zipcode/dl/utf/zip/utf_ken_all.zip

      - name: 解凍１
        if: ${{ steps.diff_check.outcome == 'failure' }}
        run: docker compose run --rm app unzip -o ./tmp/current.zip -d ./tmp/current/
      
      - name: 解凍２
        if: ${{ steps.diff_check.outcome == 'failure' }}
        run: docker compose run --rm app unzip -o ./expected/japan_postal_codes.zip -d ./tmp/expected/
      
      - name: 差分比較
        if: ${{ steps.diff_check.outcome == 'failure' }}
        run: docker compose run --rm app diff -u ./tmp/expected/utf_ken_all.csv ./tmp/current/utf_ken_all.csv
        
      - name: ワークフロー結果の確定
        if: ${{ steps.diff_check.outcome == 'failure' }}
        run: |
          echo "差分が検出されたためワークフローを失敗として終了します"
          exit 1