name: 時々変わるデータの差分検出

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の午前0時（UTC）= 日本時間月曜日午前9時
    # - cron: '0 22 * * *'
  push:
    branches:
      - main 
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: キャッシュのリストア
        uses: actions/cache@v4
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      # 中身見たいときだけ使ったほうがいい
      # - run: echo '${{ toJSON(steps) }}'

      - name: クリーンインストール
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: docker compose -f docker-compose.yml run --rm app npm ci

      - name: 差分チェック
        run: docker compose -f docker-compose.yml run --rm app npm run test
